# These are supported funding model platforms

github: Nam4ik # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Nam4ik # Replace with a single Patreon username
ko_fi: ArcaneDev # Replace with a single Ko-fi username
thanks_dev: ArcaneDev # Replace with a single thanks.dev username
custom: 'https://t.me/ArcaneDevStudio', 'https://t.me/Nam4iks'
